### ISSUE TITLE
Post sin nombre del propietario del carné

### ISSUE THREAD

**Issue by andresmauriciogomezr** [ShellSystem/loencontre.co#56]
Es posible que la api de Microsoft no reconozca el nombre de en el carné por lo que el post se irá sin nombre y retornará un error que el usuario no puede solucionar. Caso de prueba 
https://www.facebook.com/photo.php?fbid=1260257027407002&set=g.5347104545&type=1&theater
Cuando esto suceda se debería pedir al usuario que digite manualmente el nombre del carné.

**Comment by AlvaroHernandezM** [comment]
Cuando se identifique en la parte del Frontend que no se pudo encontrar o filtrar el nombre en la imagen del carné, se debe expandir un modal que permita al publicador agregar el nombre completo del propietaro del carné.
